# See ../README.md for documentation
---
- name: Apt install apache dependencies
  apt:
    name: apache2 certbot
    update_cache: no

- name: Upload Apache certbot config
  # This is a temp config we use just to get the ssl stuff done
  template:
    src: roles/apache-certbot/templates/certbot.apache.conf
    dest: /etc/apache2/sites-enabled/certbot.apache.conf
    
- name: Create certbot webroot
  file:
    path: /var/www/certbot
    state: directory
  
- name: Reload apache2 with certbot service
  systemd:
    name: apache2
    state: reloaded

- name: Clear out any old lets encrypt config
  # We don't want conf files and keys with 001 in the name
  file:
    path: /etc/letsencrypt/renewal/{{ apache_server_name }}.conf
    state: absent
    
- name: Use certbot http challenge to generate or renew ssl certs
  shell: certbot certonly -n --webroot --agree-tos --email {{ certbot_email }} -d {{ apache_server_name }} -w /var/www/certbot/
  
- name: Remove certbot webroot
  file:
    path: /var/www/certbot
    state: absent
    
- name: Remove certbot apache config
  file:
    path: /etc/apache2/sites-enabled/certbot.apache.conf
    state: absent

- name: Reload apache2 without certbot service
  systemd:
    name: apache2
    state: reloaded

- name: "Creates Let's Encrypt certificate renewal cronjob"
  cron:
    minute: "33"
    hour: "5"
    name: "Renew Let's Encrypt certificates"
    user: "root"
    job: "certbot renew -n --post-hook 'systemctl reload apache2'"
